spring:
  application:
    name: webcrawler
  data:
    redis:
      host: localhost
      port: 6379

# Elasticsearch client configuration
elasticsearch:
  hosts: [ "http://localhost:9200" ]
  username: ""
  password: ""

# Crawler configuration
crawler:
  maxDepth: 1
  queue:
    type: "redis"
  workerCount: 20
  includePatterns: [ ]
  excludePatterns: [ ]
  userAgent: "SmileyfaceWebCrawler/0.1"
  requestTimeoutMs: 10000
  queueNamespace: "crawler"
